### ISSUE TITLE
Find a way to retire `reports.json`

### ISSUE THREAD

**Issue by hidde** [hidde/eleventy-wcag-reporter#2]
Currently, report names need to be in `reports.json`, so that Eleventy knows which collections to create. 

It should be do-able to do that without explicitly listing them in `reports.json`, maybe by looking at folder names.

**Comment by petergoes** [comment]
So if I understand it correctly:

Given the folder structure:

```
reports/
	example/
		... files
	foo/
		...files
	bar/
		...files
```

You want the eleventy to have this data:

```
{  "reportNames": ["example", "foo", "bar"] }
```

The primary goal is to not need `reports.json`?

I will take a look at it tonight.
