### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by mfranzke** [hidde/eleventy-wcag-reporter#20]
Hi, this is really cool, thanks a lot !! I could provide German translation.

**Comment by hidde** [comment]
Thanks! I believe the official German WCAG 2.1 translation is almost out?

**Comment by mfranzke** [comment]
@hidde I sadly wasn't able to get any news on this – so I could provide the basis translation and would suggest to leave this open afterwards to add the WCAG version 2.1 translations as soon as those translations are officially finished.
