### ISSUE TITLE
PrinceXML not available for platform "arm-macosx11.5"

### ISSUE THREAD

**Issue by shawnthompson** [hidde/eleventy-wcag-reporter#26]
First off thanks @hidde, this is such a great project. 

When I finally got around to trying it out for an audit I was going to do on my new Mac, I got this error when I ran `rpm i`:

> PrinceXML not available for platform "arm-macosx11.5"

I'm going to remove the prince dependency until with support arm architecture. Not a deal breaker at all for me as I don't need the PDF option (for now).

Thanks again for this awesome project!

**Comment by hidde** [comment]
Thanks Shawn, that's great to hear! I have just removed the Node version of Prince from the dependencies based on your feedback.

**Comment by shawnthompson** [comment]
I also opened the following issue in the `node-prince` repo.

https://github.com/rse/node-prince/issues/36
